"""Add ICalFeed and ICalEvent models for calendar support

Revision ID: 98e37a0eed25
Revises: 70f9ada54827
Create Date: 2026-01-28 05:54:55.436788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98e37a0eed25'
down_revision = '70f9ada54827'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ical_feeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('last_fetched', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ical_feeds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ical_feeds_url'), ['url'], unique=True)

    op.create_table('ical_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feed_id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('resources', sa.Text(), nullable=True),
    sa.Column('attendee_name', sa.String(length=200), nullable=True),
    sa.Column('attendee_email', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['ical_feeds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feed_id', 'uid', name='unique_event_per_feed')
    )
    with op.batch_alter_table('ical_events', schema=None) as batch_op:
        batch_op.create_index('ix_ical_events_feed_start', ['feed_id', 'start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_ical_events_start_time'), ['start_time'], unique=False)

    with op.batch_alter_table('slideshow_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ical_feed_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ical_refresh_minutes', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_slideshow_items_ical_feed_id', 'ical_feeds', ['ical_feed_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slideshow_items', schema=None) as batch_op:
        batch_op.drop_constraint('fk_slideshow_items_ical_feed_id', type_='foreignkey')
        batch_op.drop_column('ical_refresh_minutes')
        batch_op.drop_column('ical_feed_id')

    with op.batch_alter_table('ical_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ical_events_start_time'))
        batch_op.drop_index('ix_ical_events_feed_start')

    op.drop_table('ical_events')
    with op.batch_alter_table('ical_feeds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ical_feeds_url'))

    op.drop_table('ical_feeds')
    # ### end Alembic commands ###
